plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.2-SNAPSHOT'
    id 'io.spring.dependency-management' version '1.1.7'
}

ext['spring-batch.version'] = '6.0.6-SNAPSHOT'

group = 'kr.co.wikibook'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:deprecation', '-Werror']
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-batch-jdbc'
    runtimeOnly 'com.h2database:h2'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('h2', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'org.h2.tools.Console'

    def props = new Properties()
    file('src/main/resources/application.properties').withInputStream { props.load(it) }

    args(
            '-driver', props['spring.datasource.driver-class-name'],
            '-url', props['spring.datasource.url'],
            '-user', props['spring.datasource.username']
    )
}
