spring.config.import=classpath:/job-db.properties
management.prometheus.metrics.export.pushgateway.enabled=true
management.prometheus.metrics.export.pushgateway.address=localhost:9091
management.prometheus.metrics.export.pushgateway.job=batch-jobs
management.prometheus.metrics.export.pushgateway.shutdown-operation=post
